var i = 0;
var words = [
            "cat",
            "lion",
            "art",
            "color",
            "sky",
            "ocean",
            "car",
            "red rose",
            "escape",
            "space",
            "street",
            "fog",
            "horse",
            "apple tree",
            "clone",
            "cup of coffee",
            "red label",
            "glass of water",
            "seasons",
            "clock",
            "wooden house",
            "summer forest",
            "capitan"
        ];
